src/Uploadcare/Api.php

Line 166 key_exists() change to array_key_exists()

Correct deprecated function

---

src/Uploadcare/Widget.php

now it will be visible outside class for other cms/framework plugins

widget version => const

---

changelog.md
src/Uploadcare/Widget.php

Request throttling

---

.travis.yml
changelog.md
src/Uploadcare/Api.php
src/Uploadcare/File.php
src/Uploadcare/Uploader.php
tests/ApiTest.php

keep default effects for file in groups

---

.travis.yml
AUTHORS.txt
LICENSE
README.md
changelog.md
composer.json
src/Uploadcare/Api.php
src/Uploadcare/File.php
src/Uploadcare/Group.php
src/Uploadcare/Helper.php
src/Uploadcare/Widget.php

- update changelog
- update widget to 3.x
- update authors.txt
- update travis, composer
- add deprecate warnings to deprecated methods

prepare 2.0.0 release

---

src/Uploadcare/Api.php
src/Uploadcare/File.php
tests/copyFilesTests.php

Refactored copy methods:
- Added File::createLocalCopy and File::createRemoteCopy
- Reafactored Api::copyFile
- Refactored File::copy and File::copyTo methods
- Added unit tests for File::createLocalCopy

Refactored copy methods

---

changelog.md
src/Uploadcare/File.php
tests/ApiTest.php

Added additional checks for `File` class methods

Refactored file effects and functions

---

changelog.md
src/Uploadcare/File.php
tests/ApiTest.php

- Added `File->getPath` method
- Added unit tests
- Modified `File->getUrl` method

Added File->getPath method

---

.travis.yml
composer.json
src/Uploadcare/Uploader.php
tests/ApiTest.php

This way we can supply a filename when the correct filename is not present in the URL or path of the file.

Add filename option to upload fromPath and fromContent

---

src/Uploadcare/Uploader.php

Add support for 'store' option to local uploads

---

README.md

I took the current readme + old PR from @dayton1987 (https://github.com/uploadcare/uploadcare-php/pull/74) and mixed them into a new one.

T-926 Update readme

---

src/Uploadcare/Api.php
src/Uploadcare/File.php

feature/authenticated-url - some default api params init checks added

---

composer.json
example-project/src/upload-from-path.php
example-project/src/upload-from-resource.php
example-project/src/upload-from-url.php
src/AbstractUploader.php
src/Configuration.php
src/File/UploadedFile.php
src/Interfaces/Serializer/SerializerFactoryInterface.php
src/Interfaces/UploadedFileInterface.php
src/Interfaces/UploaderInterface.php
src/Serializer/Serializer.php
src/Serializer/SerializerFactory.php
src/Uploader.php
tests/Serializer/DeserializerEdgeCasesTest.php
tests/Uploader/UploaderMethodsTest.php
tests/_data/uploaded-file.json

- make UploadedFileInterface
- implement it
- fix codestyle
Refs: #141

feat: Implement Uploaded file for upload response

---

.gitignore
.travis.yml
src/Configuration.php
src/Interfaces/SignatureInterface.php
src/Interfaces/UploadcareAuthInterface.php
src/Security/Signature.php
tests/.env
tests/GuzzleRequestTest.php
tests/SecureAuthTest.php
tests/Uploader/UploaderServiceTest.php

Implement secure auth

---

src/Configuration.php
src/File/FileCollection.php
src/FileApi.php
src/Interfaces/File/CollectionInterface.php
src/Interfaces/Response/BatchFileResponseInterface.php
src/Interfaces/Response/FileListResponseInterface.php
src/Response/BatchFileResponse.php
src/Response/FileListResponse.php
src/Response/ResponseProblem.php
src/Serializer/Serializer.php
src/Serializer/WordsConverter.php
tests/Api/FileApiAnswersTest.php
tests/Api/FileApiRemoteTest.php
tests/Api/FileApiTest.php
tests/Serializer/DeserializeCollectionTest.php
tests/_data/batch-delete-file-api-response.json
tests/_data/batch-store-file-api-response.json
tests/_data/copy-to-local-storage-api-response.json
tests/_data/copy-to-remote-storage-api-response.json
tests/_data/delete-file-api-response.json
tests/_data/file-info-api-response.json
tests/_data/file-list-api-response.json
tests/_data/store-file-api-response.json

feat: Add File API implementation

---

src/Configuration.php
tests/Configuration/ConfigurationTest.php

Closes: #158
User-agent string by template

feat: User-agent string

---

src/Api.php
src/Apis/AbstractApi.php
src/Apis/WebhookApi.php
src/Interfaces/Api/WebhookApiInterface.php
src/Interfaces/Response/WebhookInterface.php
src/Response/ProjectInfoResponse.php
src/Response/WebhookCollection.php
src/Response/WebhookResponse.php
src/Uploader/Uploader.php
src/Webhook.php
src/WebhookCollection.php
tests/Api/WebhookApiAnswersTest.php
tests/Decorated/DecoratedWebhookTest.php
tests/_data/webhook-list-response.json
tests/_data/webhook-response.json

Webhook api

---

src/Api.php
src/Apis/AbstractApi.php
src/Apis/ConversionApi.php
src/Apis/FileApi.php
src/Conversion/ConvertedItem.php
src/Conversion/DocumentConversionRequest.php
src/Conversion/DocumentConvertCollection.php
src/Exception/ConversionException.php
src/Exception/HttpException.php
src/FileCollection.php
src/Interfaces/Api/ConversionApiInterface.php
src/Interfaces/Api/FileApiInterface.php
src/Interfaces/Conversion/ConversionRequest.php
src/Interfaces/Conversion/ConvertedItemInterface.php
src/Interfaces/Conversion/DocumentConversionRequestInterface.php
src/Interfaces/Conversion/VideoConversionRequestInterface.php
src/Interfaces/Response/BatchResponseInterface.php
src/Response/BatchConvertDocumentResponse.php
src/Response/BatchFileResponse.php
src/Security/Signature.php
tests/Api/FileApiAnswersTest.php
tests/Conversion/ConversionApiMethodsTest.php
tests/Decorated/DecoratedWebhookTest.php
tests/_data/conversion/document-conversion-response.json
tests/_data/conversion/one-document-conversion-no-problem-response.json

Document conversion

---

src/Apis/ConversionApi.php
src/Conversion/ConvertedCollection.php
src/Conversion/VideoEncodingRequest.php
src/Conversion/VideoUrlBuilder.php
src/Interfaces/Api/ConversionApiInterface.php
src/Interfaces/Conversion/VideoConversionRequestInterface.php
src/Interfaces/Conversion/VideoEncodingRequestInterface.php
src/Response/BatchConversionResponse.php
tests/Conversion/ConversionApiMethodsTest.php
tests/Conversion/VideoUrlBuilderTest.php
tests/Uploader/UploaderMethodsTest.php
tests/Uploader/UploaderServiceTest.php
tests/VideoEncoding/VideoEncodingRequestTest.php
tests/_data/conversion/batch-video-conversion-result.json
tests/_data/conversion/one-video-no-error-result.json
tests/_data/conversion/one-video-with-error-result.json
tests/_data/conversion/video-conversion-status.json

Video encoding

---

README.md

Thanks for this library.
A small fix for a typo in the Readme.

fix: update typo

---

.github/workflows/phpunit.yml
CHANGELOG.md
src/File/AbstractCollection.php
src/Serializer/Serializer.php
tests/Serializer/DeserializerTest.php

Extends date format

---

CHANGELOG.md
composer.json

* Allow to use guzzlehttp/psr7:^2

Allow to use guzzlehttp/psr7:^2 (#189)

---

CHANGELOG.md
README.md
src/Apis/FileApi.php
src/Apis/GroupApi.php
src/Configuration.php
src/File/AbstractCollection.php
src/Interfaces/Api/GroupApiInterface.php
tests/Uploader/UploaderMethodsTest.php

Fix calls to removed/changed API methods

Fix calls to removed/changed API methods

---

src/Apis/FileApi.php

Allow transformation parameters on file copy

Update copy methods
